openapi: 3.0.0

info:
  version: 1.0.0
  title: TechBoard API

tags:
  - name: HealthCheck
    description: ヘルスチェック
  - name: User
    description: ユーザー
  - name: Board
    description: 掲示板
  - name: Article
    description: 記事

servers:
  - url: http://localhost:8080
    description: local server

paths:
  /health_check:
    get:
      tags:
        - HealthCheck
      summary: ヘルスチェック
      description: APIサーバの稼働状況を確認する。
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
                    example: OK
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
                    example: NG

  /v1/signup:
    post:
      tags:
        - User
      summary: ユーザー登録
      description: ユーザーを登録する。
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signupRequest"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/signupResponse"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response422"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response500"

  /v1/login:
    post:
      tags:
        - User
      summary: ユーザーログイン
      description: ユーザーログインを行う。
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginResponse"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response422"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response500"

  /v1/threads:
    get:
      tags:
        - Board
      summary: スレッド一覧取得
      description: スレッドの一覧を取得する。
      parameters:
        - name: categoryId
          in: query
          required: false
          schema:
            type: string
            description: カテゴリID
            example: "1"
        - name: page
          in: query
          required: true
          schema:
            type: integer
            description: ページ番号
            example: 1
        - name: perPage
          in: query
          required: true
          schema:
            type: integer
            description: 1ページあたりの件数
            example: 20
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/threadsListGetResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response400"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response500"

components:
  schemas:
    signupRequest:
      type: object
      description: ユーザー登録リクエスト
      required:
        - userId
        - password
        - name
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        password:
          type: string
          description: パスワード
          example: password
        name:
          type: string
          description: ニックネーム
          example: ニックネーム

    signupResponse:
      type: object
      description: ユーザー登録レスポンス
      required:
        - userId
        - name
        - createdAt
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        name:
          type: string
          description: ニックネーム
          example: ニックネーム
        createdAt:
          type: string
          description: 作成日時
          example: "2022-01-01T00:00:00+09:00"

    loginRequest:
      type: object
      description: ログインリクエスト
      required:
        - userId
        - password
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        password:
          type: string
          description: パスワード
          example: password

    loginResponse:
      type: object
      description: ログインレスポンス
      required:
        - userId
        - name
        - createdAt
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        name:
          type: string
          description: ニックネーム
          example: ニックネーム
        createdAt:
          type: string
          description: 作成日時
          example: "2022-01-01T00:00:00+09:00"

    threadsListGetResponse:
      type: object
      description: スレッド一覧取得レスポンス
      properties:
        threads:
          type: array
          description: スレッド一覧
          items:
            type: object
            description: スレッド
            required:
              - threadId
              - threadTitle
              - categoryId
              - createdAt
              - updatedAt
            properties:
              threadId:
                type: string
                description: スレッドID
                example: "1"
              threadTitle:
                type: string
                description: スレッドタイトル
                example: スレッドタイトル
              categoryId:
                type: string
                description: カテゴリID
                example: "1"
              createdAt:
                type: string
                description: 作成日時
                example: "2022-01-01T00:00:00+09:00"
              updatedAt:
                type: string
                description: 更新日時
                example: "2022-01-01T00:00:00+09:00"
        pagination:
          type: object
          description: ページネーション情報
          required:
            - page
            - perPage
            - total
          properties:
            page:
              type: integer
              description: ページ番号
              example: 1
            perPage:
              type: integer
              description: 1ページあたりの件数
              example: 20
            total:
              type: integer
              description: 総件数
              example: 99

    Response400:
      type: object
      description: 400エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ

    Response401:
      type: object
      description: 401エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ

    Response404:
      type: object
      description: 404エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ

    Response422:
      type: object
      description: 422エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ
        errors:
          type: object
          description: エラー内容
          properties:
            propertyName:
              type: string
              description: プロパティ名
              example: xxxxを入力してください。

    Response500:
      type: object
      description: 500エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ
