openapi: 3.0.0

info:
  version: 1.0.0
  title: TechBoard API

tags:
  - name: HealthCheck
    description: ヘルスチェック
  - name: User
    description: ユーザー
  - name: Board
    description: 掲示板
  - name: Article
    description: 記事

servers:
  - url: http://localhost:8080
    description: local server

paths:
  /health_check:
    get:
      tags:
        - HealthCheck
      summary: ヘルスチェック
      description: APIサーバの稼働状況を確認する。
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthCheckResponse"

  /v1/signup:
    post:
      tags:
        - User
      summary: ユーザー登録
      description: ユーザーを登録する。
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signupRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/signupResponse"

components:
  schemas:
    healthCheckResponse:
      type: object
      properties:
        status:
          type: string
          format: varchar(100)
          example: OK

    signupRequest:
      type: object
      properties:
        userId:
          type: string
          format: varchar(100)
          example: userId
        password:
          type: string
          format: varchar(100)
          example: password
        name:
          type: string
          format: varchar(100)
          example: ニックネーム

    signupResponse:
      type: object
      properties:
        userId:
          type: string
          format: varchar(100)
          example: userId
        password:
          type: string
          format: varchar(100)
          example: password
        name:
          type: string
          format: varchar(100)
          example: ニックネーム
