openapi: 3.0.0

info:
  version: 1.0.0
  title: TechBoard API

tags:
  - name: HealthCheck
    description: ヘルスチェック
  - name: User
    description: ユーザー
  - name: Board
    description: 掲示板
  - name: Article
    description: 記事

servers:
  - url: http://localhost:8080
    description: local server

paths:
  /health_check:
    get:
      tags:
        - HealthCheck
      summary: ヘルスチェック
      description: APIサーバの稼働状況を確認する。
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
                    example: OK
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
                    example: NG

  /v1/signup:
    post:
      tags:
        - User
      summary: ユーザー登録
      description: ユーザーを登録する。
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signupRequest"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/signupResponse"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response422"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response500"

  /v1/login:
    post:
      tags:
        - User
      summary: ユーザーログイン
      description: ユーザーログインを行う。
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginResponse"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response422"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response500"
  /v1/article:
    post:
      tags:
        - 記事
      summary: 記事一覧取得
      description: 記事一覧を取得する
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/articlePostRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/articlePostResponse"

components:
  schemas:
    signupRequest:
      type: object
      description: ユーザー登録リクエスト
      required:
        - userId
        - password
        - name
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        password:
          type: string
          description: パスワード
          example: password
        name:
          type: string
          description: ニックネーム
          example: ニックネーム

    signupResponse:
      type: object
      description: ユーザー登録レスポンス
      required:
        - userId
        - name
        - createdAt
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        name:
          type: string
          description: ニックネーム
          example: ニックネーム
        createdAt:
          type: string
          description: 作成日時
          example: "2022-01-01T00:00:00+09:00"

    loginRequest:
      type: object
      description: ログインリクエスト
      required:
        - userId
        - password
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        password:
          type: string
          description: パスワード
          example: password

    loginResponse:
      type: object
      description: ログインレスポンス
      required:
        - userId
        - name
        - createdAt
      properties:
        userId:
          type: string
          description: ユーザーID
          example: userId
        name:
          type: string
          description: ニックネーム
          example: ニックネーム
        createdAt:
          type: string
          description: 作成日時
          example: "2022-01-01T00:00:00+09:00"

    articlePostRequest:
      type: object
      properties:
        pageNumber:
          type: integer
          format: integer(100)
          example: 1
        perPage:
          type: integer
          format: integer(100)
          example: 10

    articlePostResponse:
      type: object
      properties:
        articleId:
          type: integer
          format: integer(100)
          example: 1
        articleName:
          type: string
          format: varchar(100)
          example: artice_name
        createdAt:
          type: string
          format: date-time
          example: "2017-01-01 12:00:00"
        updatedAt:
          type: string
          format: date-time
          example: "2017-01-01 12:00:00"
        pageNumber:
          type: integer
          format: integer(100)
          example: 1
        perPage:
          type: integer
          format: integer(100)
          example: 10
        totalNumber:
          type: integer
          format: integer(100)
          example: 10

    Response400:
      type: object
      description: 400エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ

    Response401:
      type: object
      description: 401エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ

    Response404:
      type: object
      description: 404エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ

    Response422:
      type: object
      description: 422エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ
        errors:
          type: object
          description: エラー内容
          properties:
            propertyName:
              type: string
              description: プロパティ名
              example: xxxxを入力してください。

    Response500:
      type: object
      description: 500エラーレスポンス
      properties:
        message:
          type: string
          description: メッセージ
          example: メッセージ
